/* SQL Command To Create Database */
CREATE DATABASE IF NOT EXISTS samplejsfhibernate;

/* SQL Command To Use The Database */
USE samplejsfhibernate;

/* DROP Any Exisiting Table In The Database With Name As "THESIS" */
DROP TABLE IF EXISTS THESIS;

/* SQL Command To Create The Table In A Database */

CREATE TABLE THESIS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	NAME VARCHAR(25),
	CURRICULUM INTEGER,
	ADVISOR VARCHAR(25),
	SECOND_READER VARCHAR(25),
	ACADEMIC_ASSOCIATE VARCHAR(25),
	GRADUATION_DATE DATE,
	PROBLEM_STATEMENT VARCHAR(25),
	RESEARCH_HYPOTHESIS VARCHAR(25),
	PRIMARY KEY (ID)
);